version: 2.1

orbs:
  win: circleci/windows@2.2.0
  coveralls: coveralls/coveralls@2.1.0

jobs:
  build-linux:
    parameters:
      python_version:
        type: string
    docker:
      - image: python:<< parameters.python_version >>
    steps:
      - checkout
      - run:
          name: "Set up Python environment"
          command: python -m venv venv && . venv/bin/activate

      - run:
          name: "Install latest commit of loanpy from GitHub"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Install pytest, coveralls, coverage"
          command: |
            pip install pytest
            pip install coveralls
            pip install coverage

      - run:
          name: Run tests and generate coverage report
          command: |
            coverage run --source=src -m pytest -k "not test_eval_sca_integration"
            coverage lcov

      - coveralls/upload:
          base_path: ..
          coverage_file: coverage.lcov
          #token: vSDpTEtmDXnpItx65fjti0V0pqdIekdSj

  build-windows:
    parameters:
      python_version:
        type: string
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install Python"
          command: |
            if ( "<< parameters.python_version >>" -eq "3.7" -or "<< parameters.python_version >>" -eq "3.9" ) {
              $specific_version = "3.7.0"
              if ( "<< parameters.python_version >>" -eq "3.9" ) { $specific_version = "3.9.0" }
              choco install pyenv-win --force
              refreshenv
              pyenv install $specific_version
              pyenv global $specific_version
              $env:Path = 'C:\Users\circleci\.pyenv\pyenv-win\bin;C:\Users\circleci\.pyenv\pyenv-win\shims;' + $env:Path
              python --version
            } else {
              choco install python --version=<< parameters.python_version >>
            }

      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Install pytest"
          command: pip install pytest

      - run:
          name: "Run unit and integration tests"
          command: python -m pytest

  build-macos:
    parameters:
      python_version:
        type: string
    docker: # Use the official CircleCI Python Docker image
      - image: cimg/python:<< parameters.python_version >>
    steps:
      - checkout
      - run:
          name: Set up virtual environment and install pytest
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install git+https://github.com/martino-vic/loanpy.git@2.0.1
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest


workflows:
  version: 2
  build-and-test:
    jobs:
       - build-linux:
           matrix:
             parameters:
               python_version: ["3.9"] #["3.7", "3.8", "3.9", "3.10", "3.11"]
#       - build-windows:
#           matrix:
#             parameters:
#               python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
#       - build-macos:
#          matrix:
#            parameters:
#              python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
