version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  install-python-windows:
    parameters:
      python_version:
        type: string
    steps:
      - run:
          name: "Download Python Installer"
          command: |
            $PythonUrl = "https://www.python.org/ftp/python/<< parameters.python_version >>/python-<< parameters.python_version >>-amd64.exe"
            Invoke-WebRequest -Uri $PythonUrl -OutFile "python-installer.exe" -ErrorAction SilentlyContinue -ErrorVariable WebError
            if ($WebError) {
              Write-Host "Failed to download Python installer. Exiting."
              exit 1
            }
      - run:
          name: "Install Python"
          command: |
            .\python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 TargetDir="C:\Python<< parameters.python_version >>" -ErrorAction SilentlyContinue -ErrorVariable InstallError
            if ($InstallError) {
              Write-Host "Failed to install Python. Exiting."
              exit 1
            }

jobs:
  build-linux:
    parameters:
      python_version:
        type: string
    docker:
      - image: python:<< parameters.python_version >>
    steps:
      - checkout
      - run:
          name: "Set up Python environment"
          command: python -m venv venv && . venv/bin/activate
      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1
      - run:
          name: "Run unit and integration tests"
          command: python -m pytest

  build-windows:
    parameters:
      python_version:
        type: string
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - install-python-windows:
          python_version: << parameters.python_version >>
      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1
      - run:
          name: "Run unit and integration tests"
          command: python -m pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-linux:
          matrix:
            parameters:
              python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      - build-windows:
          matrix:
            parameters:
              python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
