version: 2.1

jobs:
  build:
    parameters:
      python_version:
        type: string
    executor:
      name: python-${{ parameters.python_version }}
      runs-on: ${{ matrix.os }}
      docker:
        image: circleci/python:${{ parameters.python_version }}-stretch
    steps:
      - checkout
      - run:
          name: "Set up Python environment"
          command: |
            python -m venv venv
            if [ "${{ matrix.os }}" == "windows-latest" ]; then
              ./venv/Scripts/activate.bat
            else
              source venv/bin/activate
            fi

      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Install pytest"
          command: pip install pytest

      - run:
          name: "Run unit and integration tests"
          command: python -m pytest

    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          matrix:
            python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
