version: 2.1

executors:
  windows-2019:
    docker:
      - image: mcr.microsoft.com/windows:2019

jobs:
  build:
    parameters:
      python_version:
        type: string
    executor:
      name: windows-2019
    steps:
      - checkout
      - run:
          name: "Set up Python environment"
          command: C:\\Python\\Python${{ matrix.python_version }}\\python.exe -m venv venv && . venv\\Scripts\\activate

      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Install pytest"
          command: pip install pytest

      - run:
          name: "Run unit and integration tests"
          command: C:\\Python\\Python${{ matrix.python_version }}\\python.exe -m pytest

    matrix:
      python_version:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
