version: 2.1
orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install Python"
          command: choco install python --version=3.9.12

      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Install dependencies"
          command: pip install --user -r requirements.txt

      - run:
          name: "Run unit and integration tests"
          command: python -m pytest
