version: 2.1

jobs:
  build:
    parameters:
      python_version:
        type: string
    working_directory: C:\project
    steps:
      - checkout

      - run:
          name: "Install Python"
          command: |
            choco install python --version ${python_version} -y

      - run:
          name: "Set up Python environment"
          command: |
            python -m venv venv
            venv\Scripts\activate.bat

      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Install pytest"
          command: pip install pytest

      - run:
          name: "Run unit and integration tests"
          command: python -m pytest

  build-windows-3.11:
    working_directory: C:\project
    steps:
      - checkout

      - run:
          name: "Install Python"
          command: |
            choco install python --version 3.11.0 -y

      - run:
          name: "Set up Python environment"
          command: |
            python -m venv venv
            venv\Scripts\activate.bat

      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Install pytest"
          command: pip install pytest

      - run:
          name: "Run unit and integration tests"
          command: python -m pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          python_version: "3.7"
      - build:
          python_version: "3.8"
      - build:
          python_version: "3.9"
      - build:
          python_version: "3.10"
      - build-windows-3.11
