version: 2.1

jobs:
  build:
    parameters:
      python_version:
        type: string
    docker:
      - image: python:<< parameters.python_version >>
    steps:
      - checkout
      - run:
          name: "Set up Python environment"
          command: python -m venv venv && . venv/bin/activate

      - run:
          name: "Install latest commit of loanpy from git"
          command: pip install git+https://github.com/martino-vic/loanpy.git@2.0.1

      - run:
          name: "Run unit and integration tests"
          command: python -m pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          matrix:
            parameters:
              python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
